### ISSUE TITLE
what feature it provide?

### ISSUE THREAD

**Issue by delbao** [Zetten/bazel-sonarqube#4]
seems to me I can build with bazel and just use `sonar.java.binaries=target/classes` to make it work with sonar-scanner. What is the reason to have this plugin?

**Comment by Zetten** [comment]
Hi @delbao, good question!

There's certainly nothing stopping you manually creating the sonar-scanner.properties file and invoking the scanner manually after a build.

However, wrapping it in a rule means that Bazel can take care of setting up the `sonar.java.libraries` based on the target and its dependencies, and additionally ensuring that your classes are actually built as a prerequisite of analysis. It also brings some consistency with other Java build systems: you can do `bazel run //:my_sq_target` in just the same way you can do `mvn sonar:sonar` or `./gradlew sonarqube`.

The other main piece of this repo is the coverage report generator. Currently only tested on Java projects, this integrates with Bazel's test coverage system to produce a report which can be loaded into the `sonarqube` rule for getting coverage info in SQ. Currently I don't think this is possible any other way since Bazel's default coverage report format isn't supported by any SQ plugin.

**Comment by delbao** [comment]
gotcha. thanks for the clarity @Zetten
